---
- name: Deploy application
  hosts: app
  tags: deploy-tag
  become: true
  tasks:
    - name: Fetch latest application version
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: '/home/{{ deploy_user }}/reddit'
        version: monolith
      tags: deploy-tag
      notify: reload puma


    - name: Bundler install
      bundler:
        state: present
        chdir: '/home/{{ deploy_user }}/reddit'
      register: bundler_install_result # https://docs.ansible.com/ansible-lint/rules/default_rules.html E405
      until: bundler_install_result is succeeded
  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
