---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "comment.fullname" . }}
  labels:
    app: reddit
    component: comment
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: comment
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "comment.fullname" . }}
      labels:
        app: reddit
        component: comment
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}/comment:{{ .Values.image.tag }}"
        name: {{ template "comment.fullname" . }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: {{ template "comment.fullname" . }}
          protocol: TCP
        env:
        - name: COMMENT_DATABASE_HOST
          value: {{ .Values.databaseHost | default (printf "%s-mongodb" .Release.Name) }}
